### PR TITLE
feature: add api

### LINKED ISSUE #10: feature: add apis
Add all apis and models from the api

### PR DESCRIPTION
**Pull request by malinovic**
Still in draft...

### CODE REVIEW

**Comment by claudio-OST** [comment]
At the moment i receive an error on running 'next dev':
image

I have updated to node 20.11.1 and executed npm ci. Can you give me pointers to get rid of the error please?

**Comment by malinovic** [comment]
This normally occurs if you still use node 18. Are you sure that you use bode 20 in the console where you are running npm run dev?

**Comment by claudio-OST** [comment]
Yes, pretty sure: 
image

image

**Comment by malinovic** [comment]
And otherwise delete the node modules and do a npm ci then.

**Comment by claudio-OST** [comment]
It works when I add 'use client'; to validation.ts (File seems to not be defined in the node/server context). Is this an acceptable fix?

**Comment by malinovic** [comment]
> It works when I add 'use client'; to validation.ts (File seems to not be defined in the node/server context). Is this an acceptable fix?

No, not acceptable. Since it is something that should happen on the server side we should not add 'use client'.

**Comment by malinovic** [comment]
Small thing, instead of using `next dev` please run the project with `npm run dev`.

**Comment by claudio-OST** [comment]
Great, that solved the problem. Thanks.

**Review by claudio-OST — APPROVED** [review]
Great work. Looking forward to integrate the api

**Pull request merged**
