### PR TITLE
feat: add header actions with settings modal

### PR DESCRIPTION
**Pull request by malinovic**

### CODE REVIEW

**Comment by claudio-OST** [comment]
When the modal is visible over the user page there is a z-index problem: 
image

**Comment by claudio-OST** [comment]
there seems to be a problem with multiple changes.

- when I change my name directly after login it works correctly but when i change it again nothing happens.

**Comment by claudio-OST** [comment]
revalidation?

- when i change my username through settings the change is not reflected in the user page.
- it works on the home page but if i navigate to the user page then the old name is still visible.

**Comment by malinovic** [comment]
> there seems to be a problem with multiple changes.
> 
> * when I change my name directly after login it works correctly but when i change it again nothing happens.

Unfortunately, I am not able to reproduce it. Is it still occuring to you?

**Comment by malinovic** [comment]
> revalidation?
> 
> * when i change my username through settings the change is not reflected in the user page.
> * it works on the home page but if i navigate to the user page then the old name is still visible.

Fixed

**Comment by claudio-OST** [comment]
> > there seems to be a problem with multiple changes.
> > 
> > * when I change my name directly after login it works correctly but when i change it again nothing happens.
> 
> Unfortunately, I am not able to reproduce it. Is it still occuring to you?

Yes, I agree. The problem is gone...

**Review by claudio-OST — APPROVED** [review]
Great work. Looking forward to see this integrated...

**Pull request merged**
