### PR TITLE
feat: add tags

### PR DESCRIPTION
**Pull request by malinovic**

### CODE REVIEW

**Comment by claudio-OST** [comment]
It seems that new posts with a tag are not recognized. I made 2 new posts with the starwars tag:
image

These posts do not appear when i click on the hashtag. This is what I see: 
image

**Comment by claudio-OST** [comment]
When I search for hashtags i get a runtime error. (I see in the package.json the next is set to version "^14.1.3". In the main branch we have:   "next": "^14.2.0",

This is the error message:
image

**Comment by malinovic** [comment]
Hello @claudio-OST, the mentioned topics should be resolved now :)

**Comment by claudio-OST** [comment]
Great improvements.

2 More Questions:

1 There are posts shown without the tags below the tagged posts. I think its better to just show the tagged posts.

2 I think it would be good to show what tag has been clicked / searched for (above the search field) - I can offer to do this outside this PR in a general improvements branch/issue

**Comment by claudio-OST** [comment]
tagged posts are filtered now. that's great!

there seems to be a new problem with the search form. when i search i get this error: 
image

i havent been able to do any search input so reproducing this error should be straightforward.

**Comment by malinovic** [comment]
Hello @claudio-OST, thank you for your fast feedback. So far, I was not able to reproduce the issue.

**Review by claudio-OST — APPROVED** [review]

**Pull request merged**
